# Generated by Django 2.0.5 on 2018-05-11 04:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20180511_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='hours',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
