# Generated by Django 2.0.5 on 2018-05-23 05:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('meal_period', models.CharField(choices=[('BR', 'BREAKFAST'), ('LU', 'LUNCH'), ('DI', 'DINNER'), ('LN', 'LATENIGHT')], default='DI', max_length=2, verbose_name='meal_period')),
                ('dining_hall', models.CharField(choices=[('FE', 'FEAST'), ('BP', 'BPLATE'), ('CO', 'COVEL'), ('DN', 'DENEVE')], default='BP', max_length=2, verbose_name='dining_halls')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WaitingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_times', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(verbose_name='meal_times'), size=None)),
                ('meal_day', models.DateField(verbose_name='meal_day')),
                ('meal_period', models.CharField(choices=[('BR', 'BREAKFAST'), ('LU', 'LUNCH'), ('DI', 'DINNER'), ('LN', 'LATENIGHT')], default='DI', max_length=2, verbose_name='meal_period')),
                ('dining_halls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('FE', 'FEAST'), ('BP', 'BPLATE'), ('CO', 'COVEL'), ('DN', 'DENEVE')], default='BP', max_length=2, verbose_name='dining_halls'), size=None)),
                ('found_match', models.BooleanField(default=False, verbose_name='found_match')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
