# Generated by Django 2.0.5 on 2018-05-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20180523_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchedusers',
            name='time',
        ),
        migrations.AddField(
            model_name='matchedusers',
            name='meal_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='meal_datetime'),
        ),
    ]
