# Generated by Django 2.0.5 on 2018-05-23 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_auto_20180523_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchedusers',
            name='meal_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='meal_datetime'),
        ),
    ]
