# Generated by Django 2.0.5 on 2018-05-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_auto_20180523_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchedusers',
            name='dining_hall',
            field=models.CharField(choices=[('FE', 'FEAST'), ('BP', 'BPLATE'), ('CO', 'COVEL'), ('DN', 'DENEVE')], default='BP', max_length=2, verbose_name='dining_hall'),
        ),
    ]
