# Generated by Django 2.0.5 on 2018-05-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_auto_20180523_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchedusers',
            name='chat_url',
            field=models.TextField(default='', verbose_name='chat_url'),
        ),
    ]
