# Generated by Django 2.0.5 on 2018-06-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_matchedusers_chat_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchedusers',
            name='user1_first_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='user1_first_name'),
        ),
        migrations.AddField(
            model_name='matchedusers',
            name='user1_last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='user1_last_name'),
        ),
        migrations.AddField(
            model_name='matchedusers',
            name='user2_first_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='user2_first_name'),
        ),
        migrations.AddField(
            model_name='matchedusers',
            name='user2_last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='user2_last_name'),
        ),
    ]
