# Generated by Django 2.0.5 on 2018-06-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_auto_20180602_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchedusers',
            name='meal_period',
            field=models.CharField(choices=[('BR', 'BREAKFAST'), ('BU', 'BU'), ('LU', 'LUNCH'), ('DI', 'DINNER'), ('LN', 'LATENIGHT')], default='DI', max_length=2, verbose_name='meal_period'),
        ),
        migrations.AlterField(
            model_name='waitinguser',
            name='meal_period',
            field=models.CharField(choices=[('BR', 'BREAKFAST'), ('BU', 'BU'), ('LU', 'LUNCH'), ('DI', 'DINNER'), ('LN', 'LATENIGHT')], default='DI', max_length=2, verbose_name='meal_period'),
        ),
    ]
