# Generated by Django 2.1.3 on 2018-11-23 07:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedmenu',
            name='detailedMenu',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='overviewmenu',
            name='overviewMenu',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutrition',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
