# Generated by Django 2.1.3 on 2018-11-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20181123_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_link',
            field=models.CharField(max_length=40),
        ),
    ]
