version: "3"
services:
    # api:
    #     build: ./menu_backend
    #     ports:
    #         - "5000:5000"
    #     restart: always
    #     depends_on:
    #         - postgres
    #     env_file:
    #         - node.dev.env
    #     networks:
    #         - webnet

    # menu:
    #     build: ./menu_backend
    #     ports:
    #         - "5000:8000"
    #     restart: always
    #     depends_on:
    #         - postgres
    #     env_file:
    #         menu.dev.env
    #     networks:
    #         - webnet

    users:
        build: ./user_backend
        ports:
            - "8000:8000"
        restart: on-failure
        volumes:
            - ./user_backend:/app/BruinBite/users
        depends_on:
            - postgres
        env_file:
            - users.dev.env
        networks:
            - webnet

    postgres:
        image: postgres:10.2-alpine
        ports:
            - "5432:5432"
        restart: always
        env_file:
            - postgres.dev.env
        networks:
            - webnet

networks:
    webnet:

