version: "3"
services:
    web:
        # build: .
        image: terrenceho/dea-backend:latest
        ports:
            - "5000:5000"
        depends_on:
            - postgres
        env_file:
            - node.env
        networks:
            - webnet
    postgres:
        image: postgres:10.2-alpine
        ports:
            - "5432:5432"
        restart: always
        env_file:
            - postgres.env
        networks:
            - webnet
networks:
    webnet:
