version: "3"
services:
    api:
        build: ./menu_backend
        ports:
            - "5000:5000"
        restart: always
        depends_on:
            - postgres
        env_file:
            - node.dev.env
        networks:
            - webnet

    postgres:
        image: postgres:10.2-alpine
        ports:
            - "5432:5432"
        restart: always
        env_file:
            - postgres.dev.env
        networks:
            - webnet

networks:
    webnet:

