version: "3"
services:
    api:
        build: ./menu_backend
        ports:
            - "5000:5000"
        restart: always
        depends_on:
            - postgres
        env_file:
            - node.env
        networks:
            - webnet

    users:
        build: ./user_backend
        ports:
            - "8000:8000"
        restart: always
        depends_on:
            - postgres
        env_file:
            - users.env
        networks:
            - webnet

    postgres:
        image: postgres:10.2-alpine
        ports:
            - "5432:5432"
        restart: always
        env_file:
            - postgres.env
        networks:
            - webnet

    caddy:
        image: abiosoft/caddy
        restart: always
        depends_on:
            - api
            - postgres
        ports:
            - "80:80"
            - "443:443"
        networks:
            - webnet
        volumes:
            - ./.caddy:/root/.caddy
            - ./Caddyfile:/etc/Caddyfile


networks:
    webnet:
