# Generated by Django 2.0.5 on 2018-05-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(default='', max_length=150, verbose_name='device_id'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_on_chat',
            field=models.BooleanField(default=False, verbose_name='is_on_chat'),
        ),
    ]
