# Generated by Django 2.0.4 on 2018-04-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180429_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='year'),
        ),
    ]
