# Generated by Django 2.0.5 on 2018-06-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180525_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='device_id'),
        ),
    ]
