# Generated by Django 2.0.5 on 2019-06-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180602_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='announce_notify',
            field=models.BooleanField(default=False, verbose_name='announce_notify'),
        ),
        migrations.AddField(
            model_name='user',
            name='chat_notify',
            field=models.BooleanField(default=False, verbose_name='chat_notify'),
        ),
        migrations.AddField(
            model_name='user',
            name='match_notify',
            field=models.BooleanField(default=False, verbose_name='match_notify'),
        ),
    ]
