# Generated by Django 2.0.5 on 2019-11-14 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180602_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_deleted', models.DateTimeField(auto_now_add=True, verbose_name='date_deleted')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
