# Generated by Django 2.0.5 on 2019-04-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180602_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic_url',
            field=models.TextField(blank=True, verbose_name='profile_pic_url'),
        ),
    ]
