# Generated by Django 2.0.5 on 2019-04-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_pic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic_url',
        ),
    ]
