# Generated by Django 2.0.5 on 2019-11-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0011_report'),
        ('oauth2_provider', '0006_auto_20171214_2232'),
        ('chat', '0003_auto_20190517_0119'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('users', '0004_deleteduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleteduser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='DeletedUser',
        ),
    ]
