# Generated by Django 2.0.5 on 2019-11-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191114_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deleted', models.DateTimeField(auto_now_add=True, verbose_name='date_deleted')),
                ('email', models.EmailField(default='', max_length=255, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=40, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last_name')),
                ('major', models.CharField(blank=True, max_length=150, verbose_name='major')),
                ('minor', models.CharField(blank=True, max_length=150, verbose_name='minor')),
                ('year', models.IntegerField(blank=True, default=0, null=True, verbose_name='year')),
                ('self_bio', models.TextField(blank=True, verbose_name='self_bio')),
                ('is_on_chat', models.BooleanField(default=False, verbose_name='is_on_chat')),
                ('device_id', models.CharField(blank=True, default='', max_length=150, verbose_name='device_id')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('is_staff', models.BooleanField(default=True, verbose_name='staff status')),
            ],
        ),
    ]
