# Generated by Django 2.0.5 on 2019-11-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_deleteduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteduser',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email'),
        ),
    ]
