# Generated by Django 2.0.5 on 2018-05-10 20:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylevel',
            name='level',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
