# Generated by Django 2.0.5 on 2018-05-10 20:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20180510_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverviewMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overviewMenu', django.contrib.postgres.fields.jsonb.JSONField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('menuDate', models.DateField()),
            ],
        ),
    ]
