# Generated by Django 2.0.5 on 2018-05-11 04:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20180510_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('hourDate', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='detailedmenu',
            name='detailedMenu',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='overviewmenu',
            name='overviewMenu',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
