# Generated by Django 2.0.5 on 2018-11-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_auto_20180511_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='item_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
