# Generated by Django 2.0.5 on 2018-11-30 05:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_auto_20181127_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='nutrition',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
