FEAST = "FE"
BPLATE = "BP"
COVEL = "CO"
DENEVE = "DN"

DINING_HALL_CHOICES = (
    (FEAST, "FEAST"),
    (BPLATE, "BPLATE"),
    (COVEL, "COVEL"),
    (DENEVE, "DENEVE"),
)

BREAKFAST = "BR"
BRUNCH = "BU"
LUNCH = "LU"
DINNER = "DI"
LATENIGHT = "LN"

MEAL_PERIOD_CHOICES = (
    (BREAKFAST, "BREAKFAST"),
    (BRUNCH, "BU"),
    (LUNCH, "LUNCH"),
    (DINNER, "DINNER"),
    (LATENIGHT, "LATENIGHT"),
)

MONDAY = "Mon"
TUESDAY = "Tue"
WEDNESDAY = "Wed"
THURSDAY = "Thu"
FRIDAY = "Fri"
SATURDAY = "Sat"
SUNDAY = "Sun"

MEAL_DAY_CHOICES = (
    (MONDAY, "MONDAY"),
    (TUESDAY, "TUESDAY"),
    (WEDNESDAY, "WEDNESDAY"),
    (THURSDAY, "THURSDAY"),
    (FRIDAY, "FRIDAY"),
    (SATURDAY, "SATURDAY"), 
    (SUNDAY, "SUNDAY"),
)

CANCELLED = 'C'
SUCCESS = 'S'
PENDING = 'P'
TIMEOUT = 'T'

REQUEST_STATUS_CHOICES = (
    (CANCELLED, "CANCELLED"),
    (SUCCESS, "SUCCESS"),
    (PENDING, "PENDING"),
    (TIMEOUT, "TIMEOUT")
)


