{
 "title": "Bruin Bite",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Matches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_created,3d),\n  count(id) AS \"# requested\"\nFROM matching_waitinguser\nWHERE\n  $__timeFilter(date_created)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_created,3d),\n  count(id) AS \"# fulfilled\"\nFROM matching_matchedusers\nWHERE\n  $__timeFilter(date_created)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "User signups",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_created,$__interval),\n  count(id) AS \"count\"\nFROM users_user\nWHERE\n  $__timeFilter(date_created)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "User count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) AS \"*\"\nFROM users_user"
    }
   ]
  }
 ]
}