# Generated by Django 2.0.5 on 2018-05-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180527_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
